### ISSUE TITLE
Add support for /boot/efi/EFI/BOOT/BOOTX64.efi signing

### ISSUE THREAD

**Issue by TylerHelt0** [noahbliss/mortar#12]
BOOTX64.efi is the default bootloader for a gpt drive if no boot variables are defined. On Ubuntu it is shim but on some others such as Pop it is a copy of systemd-boot.
If this binary is not signed boot can fail regardless of the distribution if the user removes microsoft's key from their secureboot variables.

**Comment by noahbliss** [comment]
@TylerHelt0 thanks for the message! Mortar's security model relies on signing the combined kernel/initramfs file directly and only using that to boot. Shim unfortunately has a major security flaw which allows an attacker to hijack the boot process by modifying the initramfs which is not signed in any implementation I've yet come across.

Secureboot itself only verifies the efi file booted by the bios, after that it is on the OS to extend that trust and perform any additional checks, by putting everything in that first efi file,we work around this limitation. 

Similarly, Mortar also relies on using your own keys in secureboot. Otherwise any bootloader signed by Microsoft could allow the TPM to release keys. Since vulnerable signed bootloaders are already out there, I consider that entire chain of trust compromised. By using your own keys and only signing your own efi files, you can guarantee outside bootloaders won't pass your system's checks.

Does this make sense? I can add some sources and additional detail but I'm on my phone keyboard at the moment.

**Comment by TylerHelt0** [comment]
I understand that in the scenario the kernel and initramfs are separate the kernel is the only plaintext file hashed and verified by Secureboot, leaving initramfs open to modification unless DM-verity or similar is implemented. 

Hmm, I should remove Microsoft's keys. I kept them for easy booting of live cds and such.

Perhaps I will merge a Pop_OS branch that addresses the recovery partition and boot entry/recovery upgrades/signing. I only point out the BOOTX64.efi for redundancy and compliance. BOOTX64.efi is a copy of the boot loader. If the uefi loses its entry for the kernel for some reason, that's where it looks on the hard drive. If it's a copy of the unified kernel image, the disk will still boot normally. Or perhaps it could be default location of mortar linux to save space. 

Aside: Ugh... trying to get automatic kernel module signing working is a pain as well. Neccessary for things like virtualbox.

**Comment by noahbliss** [comment]
@TylerHelt0 I appreciate the comments and we may revisit this later. I think for now we'll probably want to see how this unfolds for the community on the whole with the various other distros as a risk impact assessment. 

And yes, removing MS's keys and enforcing secureboot is a big decision, definitely does its job of disabling boot of things that shouldn't be, and if we're honest, using live cd's and whatnot _really shouldn't_ be something we do on the devices we trust with our data. That would really be more appropriate on a dev machine of some sort. 

Re your aside: this is why I use AMD GPUs ;P

**Comment by TylerHelt0** [comment]
On the topic of signing, your friend snawoot has two files in his repo that are plug and play with mortar besdies changing the path to the db.key and db.crt.der. 
chain-sign-hook.conf ( which defines location of db files) and setup_dkms.sh. Perhaps they can be used with his permission.
